// Flag components will be generated by the script
// For now, we'll create a few sample flags manually

import React from 'react';
import Svg, { Path, Rect, Circle } from 'react-native-svg';

// Sample flag components (US, GB, CA, AE, FR, DE, ES, IT, BR, MX, JP, CN, IN, RU, SA)

const US: React.FC<{ width: number; height: number }> = ({ width, height }) => (
  <Svg width={width} height={height} viewBox="0 0 60 30">
    <Rect width="60" height="30" fill="#B22234" />
    <Path d="M0,3.46h60M0,6.92h60M0,10.38h60M0,13.84h60M0,17.3h60M0,20.76h60M0,24.22h60M0,27.68h60" stroke="#fff" strokeWidth="2.3" />
    <Rect width="24" height="17.3" fill="#3C3B6E" />
  </Svg>
);

const GB: React.FC<{ width: number; height: number }> = ({ width, height }) => (
  <Svg width={width} height={height} viewBox="0 0 60 30">
    <Rect width="60" height="30" fill="#012169" />
    <Path d="M0,0 L60,30 M60,0 L0,30" stroke="#fff" strokeWidth="6" />
    <Path d="M0,0 L60,30 M60,0 L0,30" stroke="#C8102E" strokeWidth="4" />
    <Path d="M30,0 v30 M0,15 h60" stroke="#fff" strokeWidth="10" />
    <Path d="M30,0 v30 M0,15 h60" stroke="#C8102E" strokeWidth="6" />
  </Svg>
);

const CA: React.FC<{ width: number; height: number }> = ({ width, height }) => (
  <Svg width={width} height={height} viewBox="0 0 60 30">
    <Rect width="15" height="30" fill="#FF0000" />
    <Rect x="15" width="30" height="30" fill="#FFFFFF" />
    <Rect x="45" width="15" height="30" fill="#FF0000" />
    <Path d="M30,8 l2,6 l6,0 l-5,4 l2,6 l-5-4 l-5,4 l2-6 l-5-4 l6,0 z" fill="#FF0000" />
  </Svg>
);

const AE: React.FC<{ width: number; height: number }> = ({ width, height }) => (
  <Svg width={width} height={height} viewBox="0 0 60 30">
    <Rect width="60" height="10" fill="#00732F" />
    <Rect y="10" width="60" height="10" fill="#FFFFFF" />
    <Rect y="20" width="60" height="10" fill="#000000" />
    <Rect width="20" height="30" fill="#FF0000" />
  </Svg>
);

const FR: React.FC<{ width: number; height: number }> = ({ width, height }) => (
  <Svg width={width} height={height} viewBox="0 0 60 30">
    <Rect width="20" height="30" fill="#002395" />
    <Rect x="20" width="20" height="30" fill="#FFFFFF" />
    <Rect x="40" width="20" height="30" fill="#ED2939" />
  </Svg>
);

const DE: React.FC<{ width: number; height: number }> = ({ width, height }) => (
  <Svg width={width} height={height} viewBox="0 0 60 30">
    <Rect width="60" height="10" fill="#000000" />
    <Rect y="10" width="60" height="10" fill="#DD0000" />
    <Rect y="20" width="60" height="10" fill="#FFCE00" />
  </Svg>
);

const ES: React.FC<{ width: number; height: number }> = ({ width, height }) => (
  <Svg width={width} height={height} viewBox="0 0 60 30">
    <Rect width="60" height="7.5" fill="#AA151B" />
    <Rect y="7.5" width="60" height="15" fill="#F1BF00" />
    <Rect y="22.5" width="60" height="7.5" fill="#AA151B" />
  </Svg>
);

const IT: React.FC<{ width: number; height: number }> = ({ width, height }) => (
  <Svg width={width} height={height} viewBox="0 0 60 30">
    <Rect width="20" height="30" fill="#009246" />
    <Rect x="20" width="20" height="30" fill="#FFFFFF" />
    <Rect x="40" width="20" height="30" fill="#CE2B37" />
  </Svg>
);

const BR: React.FC<{ width: number; height: number }> = ({ width, height }) => (
  <Svg width={width} height={height} viewBox="0 0 60 30">
    <Rect width="60" height="30" fill="#009739" />
    <Path d="M30,5 L55,15 L30,25 L5,15 Z" fill="#FEDD00" />
    <Circle cx="30" cy="15" r="5" fill="#002776" />
  </Svg>
);

const MX: React.FC<{ width: number; height: number }> = ({ width, height }) => (
  <Svg width={width} height={height} viewBox="0 0 60 30">
    <Rect width="20" height="30" fill="#006847" />
    <Rect x="20" width="20" height="30" fill="#FFFFFF" />
    <Rect x="40" width="20" height="30" fill="#CE1126" />
  </Svg>
);

const JP: React.FC<{ width: number; height: number }> = ({ width, height }) => (
  <Svg width={width} height={height} viewBox="0 0 60 30">
    <Rect width="60" height="30" fill="#FFFFFF" />
    <Circle cx="30" cy="15" r="9" fill="#BC002D" />
  </Svg>
);

const CN: React.FC<{ width: number; height: number }> = ({ width, height }) => (
  <Svg width={width} height={height} viewBox="0 0 60 30">
    <Rect width="60" height="30" fill="#DE2910" />
    <Path d="M10,6 l1.5,4.5 l4.5,0 l-3.5,2.5 l1.5,4.5 l-3.5-2.5 l-3.5,2.5 l1.5-4.5 l-3.5-2.5 l4.5,0 z" fill="#FFDE00" />
  </Svg>
);

const IN: React.FC<{ width: number; height: number }> = ({ width, height }) => (
  <Svg width={width} height={height} viewBox="0 0 60 30">
    <Rect width="60" height="10" fill="#FF9933" />
    <Rect y="10" width="60" height="10" fill="#FFFFFF" />
    <Rect y="20" width="60" height="10" fill="#138808" />
    <Circle cx="30" cy="15" r="4" fill="none" stroke="#000080" strokeWidth="0.5" />
  </Svg>
);

const RU: React.FC<{ width: number; height: number }> = ({ width, height }) => (
  <Svg width={width} height={height} viewBox="0 0 60 30">
    <Rect width="60" height="10" fill="#FFFFFF" />
    <Rect y="10" width="60" height="10" fill="#0039A6" />
    <Rect y="20" width="60" height="10" fill="#D52B1E" />
  </Svg>
);

const SA: React.FC<{ width: number; height: number }> = ({ width, height }) => (
  <Svg width={width} height={height} viewBox="0 0 60 30">
    <Rect width="60" height="30" fill="#165B33" />
    <Rect x="10" y="12" width="40" height="6" fill="#FFFFFF" />
  </Svg>
);

const AU: React.FC<{ width: number; height: number }> = ({ width, height }) => (
  <Svg width={width} height={height} viewBox="0 0 60 30">
    <Rect width="60" height="30" fill="#012169" />
    <Path d="M0,0 L15,7.5 M15,0 L0,7.5" stroke="#fff" strokeWidth="1.5" />
    <Path d="M7.5,0 v7.5 M0,3.75 h15" stroke="#fff" strokeWidth="2.5" />
    <Path d="M7.5,0 v7.5 M0,3.75 h15" stroke="#C8102E" strokeWidth="1.5" />
  </Svg>
);

// Additional flags for more countries
const NL: React.FC<{ width: number; height: number }> = ({ width, height }) => (
  <Svg width={width} height={height} viewBox="0 0 60 30">
    <Rect width="60" height="10" fill="#AE1C28" />
    <Rect y="10" width="60" height="10" fill="#FFFFFF" />
    <Rect y="20" width="60" height="10" fill="#21468B" />
  </Svg>
);

const BE: React.FC<{ width: number; height: number }> = ({ width, height }) => (
  <Svg width={width} height={height} viewBox="0 0 60 30">
    <Rect width="20" height="30" fill="#000000" />
    <Rect x="20" width="20" height="30" fill="#FDDA24" />
    <Rect x="40" width="20" height="30" fill="#EF3340" />
  </Svg>
);

const CH: React.FC<{ width: number; height: number }> = ({ width, height }) => (
  <Svg width={width} height={height} viewBox="0 0 60 30">
    <Rect width="60" height="30" fill="#FF0000" />
    <Rect x="22" y="10" width="16" height="10" fill="#FFFFFF" />
    <Rect x="26" y="6" width="8" height="18" fill="#FFFFFF" />
  </Svg>
);

const SE: React.FC<{ width: number; height: number }> = ({ width, height }) => (
  <Svg width={width} height={height} viewBox="0 0 60 30">
    <Rect width="60" height="30" fill="#006AA7" />
    <Rect x="16" width="8" height="30" fill="#FECC00" />
    <Rect y="11" width="60" height="8" fill="#FECC00" />
  </Svg>
);

const NO: React.FC<{ width: number; height: number }> = ({ width, height }) => (
  <Svg width={width} height={height} viewBox="0 0 60 30">
    <Rect width="60" height="30" fill="#BA0C2F" />
    <Rect x="16" width="8" height="30" fill="#FFFFFF" />
    <Rect y="11" width="60" height="8" fill="#FFFFFF" />
    <Rect x="18" y="1" width="4" height="28" fill="#00205B" />
    <Rect x="1" y="13" width="58" height="4" fill="#00205B" />
  </Svg>
);

const DK: React.FC<{ width: number; height: number }> = ({ width, height }) => (
  <Svg width={width} height={height} viewBox="0 0 60 30">
    <Rect width="60" height="30" fill="#C8102E" />
    <Rect x="16" width="6" height="30" fill="#FFFFFF" />
    <Rect y="12" width="60" height="6" fill="#FFFFFF" />
  </Svg>
);

const FI: React.FC<{ width: number; height: number }> = ({ width, height }) => (
  <Svg width={width} height={height} viewBox="0 0 60 30">
    <Rect width="60" height="30" fill="#FFFFFF" />
    <Rect x="16" width="8" height="30" fill="#003580" />
    <Rect y="11" width="60" height="8" fill="#003580" />
  </Svg>
);

const PL: React.FC<{ width: number; height: number }> = ({ width, height }) => (
  <Svg width={width} height={height} viewBox="0 0 60 30">
    <Rect width="60" height="15" fill="#FFFFFF" />
    <Rect y="15" width="60" height="15" fill="#DC143C" />
  </Svg>
);

const GR: React.FC<{ width: number; height: number }> = ({ width, height }) => (
  <Svg width={width} height={height} viewBox="0 0 60 30">
    <Rect width="60" height="30" fill="#0D5EAF" />
    <Rect y="3.33" width="60" height="3.33" fill="#FFFFFF" />
    <Rect y="10" width="60" height="3.33" fill="#FFFFFF" />
    <Rect y="16.67" width="60" height="3.33" fill="#FFFFFF" />
    <Rect y="23.33" width="60" height="3.33" fill="#FFFFFF" />
  </Svg>
);

const PT: React.FC<{ width: number; height: number }> = ({ width, height }) => (
  <Svg width={width} height={height} viewBox="0 0 60 30">
    <Rect width="24" height="30" fill="#006600" />
    <Rect x="24" width="36" height="30" fill="#FF0000" />
    <Circle cx="24" cy="15" r="6" fill="#FFFF00" />
  </Svg>
);

const TR: React.FC<{ width: number; height: number }> = ({ width, height }) => (
  <Svg width={width} height={height} viewBox="0 0 60 30">
    <Rect width="60" height="30" fill="#E30A17" />
    <Circle cx="22" cy="15" r="6" fill="#FFFFFF" />
    <Circle cx="24" cy="15" r="5" fill="#E30A17" />
    <Path d="M32,10 l1.5,4.5 l4.5,0 l-3.5,2.5 l1.5,4.5 l-3.5-2.5 l-3.5,2.5 l1.5-4.5 l-3.5-2.5 l4.5,0 z" fill="#FFFFFF" />
  </Svg>
);

const ZA: React.FC<{ width: number; height: number }> = ({ width, height }) => (
  <Svg width={width} height={height} viewBox="0 0 60 30">
    <Rect width="60" height="10" fill="#E03C31" />
    <Rect y="10" width="60" height="10" fill="#FFFFFF" />
    <Rect y="20" width="60" height="10" fill="#007749" />
    <Path d="M0,0 L20,15 L0,30 Z" fill="#000000" />
    <Path d="M0,3 L17,15 L0,27 Z" fill="#FFB612" />
  </Svg>
);

const AR: React.FC<{ width: number; height: number }> = ({ width, height }) => (
  <Svg width={width} height={height} viewBox="0 0 60 30">
    <Rect width="60" height="10" fill="#74ACDF" />
    <Rect y="10" width="60" height="10" fill="#FFFFFF" />
    <Rect y="20" width="60" height="10" fill="#74ACDF" />
    <Circle cx="30" cy="15" r="3" fill="none" stroke="#F6B40E" strokeWidth="0.5" />
  </Svg>
);

const KR: React.FC<{ width: number; height: number }> = ({ width, height }) => (
  <Svg width={width} height={height} viewBox="0 0 60 30">
    <Rect width="60" height="30" fill="#FFFFFF" />
    <Circle cx="30" cy="15" r="6" fill="#C60C30" />
    <Circle cx="30" cy="15" r="3" fill="#003478" />
  </Svg>
);

const ID: React.FC<{ width: number; height: number }> = ({ width, height }) => (
  <Svg width={width} height={height} viewBox="0 0 60 30">
    <Rect width="60" height="15" fill="#FF0000" />
    <Rect y="15" width="60" height="15" fill="#FFFFFF" />
  </Svg>
);

const TH: React.FC<{ width: number; height: number }> = ({ width, height }) => (
  <Svg width={width} height={height} viewBox="0 0 60 30">
    <Rect width="60" height="5" fill="#ED1C24" />
    <Rect y="5" width="60" height="5" fill="#FFFFFF" />
    <Rect y="10" width="60" height="10" fill="#241D4F" />
    <Rect y="20" width="60" height="5" fill="#FFFFFF" />
    <Rect y="25" width="60" height="5" fill="#ED1C24" />
  </Svg>
);

// Export map of flag components
export const flagComponents: Record<string, React.FC<{ width: number; height: number }>> = {
  US,
  GB,
  CA,
  AE,
  FR,
  DE,
  ES,
  IT,
  BR,
  MX,
  JP,
  CN,
  IN,
  RU,
  SA,
  AU,
  NL,
  BE,
  CH,
  SE,
  NO,
  DK,
  FI,
  PL,
  GR,
  PT,
  TR,
  ZA,
  AR,
  KR,
  ID,
  TH,
};

